apiVersion: v1
kind: Pod
metadata:
  name: confluentcontrol
  namespace: kafka
spec:
  containers:
  - name: kafka
    image: confluentinc/cp-enterprise-control-center:4.1.0
    command:
      - sh
      - -c
      - "exec tail -f /dev/null"
